### ISSUE TITLE
OSXAWTwrapper.main() unused app variable

### ISSUE THREAD

**Issue by gselzer** [hanslovsky/imglyb#17]
[This line](https://github.com/imglib/imglyb/blob/40e7b255d258f3586e0beb4b0fa5186bf03fbc2b/src/imglyb/OSXAWTwrapper.py#L92) is not PEP8-compliant, as `app` is an unused variable. But, looking at the [documentation](https://developer.apple.com/documentation/appkit/nsapplication/1428360-sharedapplication?language=objc), I am hesitant to delete it as it creates an application instance if it does not exist. Can we just delete this? (cc @ctrueden, the author of said line).

Unfortunately, this code is not tested :frowning:

**Comment by gselzer** [comment]
Fixes should be added to #18, as that PR is blocked by this flaking error.

**Comment by ctrueden** [comment]
Why not just remove the `app =` portion, and write `NSApplication.sharedApplication()` ? Edit: I pushed it.

And yeah, this code cannot be tested on non-Mac platforms.

This code is mostly obsolete anyway, thanks to `jpype.setupGuiEnvironment`. But I'm hesitant to delete it nonetheless, in case it is useful in the future...

**Comment by gselzer** [comment]
> Why not just remove the `app =` portion, and write `NSApplication.sharedApplication()` ? Edit: I pushed it.

Eh, we can, I was hoping that we could either delete it or document it...

> And yeah, this code cannot be tested on non-Mac platforms.

We can just write a test that only runs if the platform is Mac? It will always be tested by Github Actions...

Anyways, thank you for making that change!

**Comment by ctrueden** [comment]
> We can just write a test that only runs if the platform is Mac?

If you have time, go for it. But it is not very important. That code is unlikely to change again, and now it passes the linter.
